language: python
dist: bionic
os: linux
python:
  - "3.11"
script:
  - black . --check
  - flake8 --max-line-length=100
  - coverage run manage.py test
install:
  - pip install -r requirements.txt
after_success:
  coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  region: "us-west-2"
  app: "django-app"
  env: "test-env-for-django"
  bucket_name: "elasticbeanstalk-us-west-2-143430868238"
  on:
    branch: main