branch-defaults:
  main:
    environment: test-env-for-django
environment-defaults:
  test-env-for-django:
    branch: null
    repository: null
global:
  application_name: django-app
  default_ec2_keyname: aws-eb2
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
